### PR TITLE
Fix slack nullpointer issue 

### LINKED ISSUE #5508: AlarmCore -78603097 [pool-2-thread-1] ERROR
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why will appear this error message

‘‘
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265],
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265],
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265],
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265],
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265],
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265],
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265],
	at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$start$3(AlarmCore.java:77) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265],
	at org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore.lambda$null$2(AlarmCore.java:77) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
	at org.apache.skywalking.oap.server.core.alarm.provider.slack.SlackhookCallback.doAlarm(SlackhookCallback.java:66) ~[server-alarm-plugin-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT],
java.lang.NullPointerException: null,
2020-09-17 07:04:21,143 - org.apache.skywalking.oap.server.core.alarm.provider.AlarmCore -78603097 [pool-2-thread-1] ERROR [] - null
‘’
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.x ，linux Centos 7

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by xbkaishui**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bug fix

- Related issues
resolved #5508
___
### Bug fix
- Bug description.
 Slack webHook throws nullpointer exception when user not set the configuration
- How to fix?
Check the null of SlackSettings

### CODE REVIEW

**Review by JaredTan95 — APPROVED** [review]
LGTM

File: oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java [hunk 1]
```diff
@@ -77,31 +77,26 @@ public void doAlarm(List<AlarmMessage> alarmMessages) {
...
                     if (statusLine != null && statusLine.getStatusCode() != HttpStatus.SC_OK) {
-                        log.error("send alarm to " + url + " failure. Response code: " + statusLine.getStatusCode());
+                        log.error("Send slack alarm to {} failure. Response code: {}", url , statusLine.getStatusCode());
                     }
                 } catch (UnsupportedEncodingException e) {
-                    log.error("Alarm to JSON error, " + e.getMessage(), e);
+                    log.error("Alarm to JSON error, {} ", e.getMessage(), e);
                 } catch (IOException e) {
-                    log.error("send alarm to " + url + " failure.", e);
+                    log.error("Send slack alarm to {} failure.", url , e);
```
Comment (wu-sheng) [inline oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java:99]: Actually, I think this should not change, but wechat callback should be changed.

Take a look on the source codes
```
public void error(Marker marker, String format, Object arg);

public void error(String msg, Throwable t);
```

If you want to print exception stack, then can't use the arguments for log text.

**Review by wu-sheng — CHANGES_REQUESTED** [review]

File: oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java (hunk 1 above)
Comment (xbkaishui) [reply oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java:99]: I don't think so , actually It will match   this method   public void error(String format, Object arg1, Object arg2), 
please check below simple test 
```
  @Test
    public void testLog() {
        try {
            int a = 1 / 0;
        } catch (Throwable e) {
            log.error("aha err {}", "formated error", e);
        }
    }

logs as belows ........


      2020-09-17 16:45:52.749  LogTest.java:22
      - aha err formated error

java.lang.ArithmeticException: / by zero
	at com.credigo.czs.service.LogTest.testLog(LogTest.java:20) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) ~[junit-4.12.jar:4.12]
```

Comment (wu-sheng) [reply oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java:99]: Thanks for the demo codes. Interesting, the comments of methods are not consistent.

**Review by wu-sheng — APPROVED** [review]

File: oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java (hunk 1 above)
Comment (xbkaishui) [reply oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/slack/SlackhookCallback.java:99]: please check [this](https://gist.github.com/xbkaishui/5afaee39e862ef38c2daaae954140340)
