### PR TITLE
Fix #6835 Add compatibility with Kafka client version 2.8.x

### LINKED ISSUE #6835: Improve compatibility with Kafka client version 2.8.x
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement
- Using Skywaking agent for Kafka client version 2.8.1 does not work as the constructor of KafkaConsumer has changed. Earlier it use to take ConsumerConfig as a parameter and now it takes Map. Thus ConsumerConstructorInterceptor is not invoked during KafkaConsumer constructor. And finally following exception is resulted from Skywalking Agent logs

```
main InstMethodsInter : class[class org.apache.kafka.clients.consumer.KafkaConsumer] before method[pollForFetches] intercept failure
java.lang.NullPointerException
	at org.apache.skywalking.apm.plugin.kafka.KafkaConsumerInterceptor.beforeMethod(KafkaConsumerInterceptor.java:52)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
```

### PR DESCRIPTION
**Pull request by divyakumarjain**
Kafka Consumer interceptor is improved to intercept constructor with Map and ConsumerConfig parameters

### Fix #6835 
- [X] Add a unit test to verify that the fix works.
- [X] Explain briefly why the bug exists and how to fix it.

Using Skywaking agent for Kafka client version 2.8.1 does not work as the constructor of KafkaConsumer has changed. Earlier it use to take ConsumerConfig as a parameter and now it takes Map. Thus ConsumerConstructorInterceptor is not invoked during KafkaConsumer constructor. The interceptor is improved to support both types of kafkaConsumer constructors.

### CODE REVIEW

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java [hunk 1]
```diff
@@ -22,18 +22,49 @@
...
 
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.List;
+import java.util.Map;
+import java.util.stream.Collectors;
+
 /**
- *
+ * @author zhang xin, stalary
```
Comment (wu-sheng) [inline apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:32]: Please remove this, we don't recommend the author information in the ASF.

**Comment by wu-sheng** [comment]
As you are adding support to a new version, you need to update the existing test cases. 
https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/kafka-scenario/support-version.list

Before you submit, please run the test case locally, and make sure it passed first. If you don't know how to run this, check the plugin development doc, it is there.

**Comment by wu-sheng** [comment]
`Supported-list.md` and `CHANGES.md` should be updated accordingly.

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java [hunk 2]
```diff
@@ -22,18 +22,49 @@
...
+    private ConsumerEnhanceRequiredInfo resolveConsumerEnhanceRequiredInfo( Object configArgument )
+    {
+        ConsumerEnhanceRequiredInfo requiredInfo = new ConsumerEnhanceRequiredInfo();
+
+        if(configArgument instanceof ConsumerConfig) {
+            ConsumerConfig config = (ConsumerConfig) configArgument;
+            // set the bootstrap server address
+            requiredInfo.setBrokerServers(config.getList("bootstrap.servers"));
+            requiredInfo.setGroupId(config.getString("group.id"));
+        } else if (configArgument instanceof Map ) {
```
Comment (wu-sheng) [inline apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:50]: This ConsumerConfig and Map logic should be separated into 2 interceptors, rather than using `instanceof` to check.
Even here, we should not face performance impact as this is `KafkaConsumer` initialization, so wouldn't execute in high frequency, but still, better to avoid any tiny performance impact. 
@kezhenxu94 What do you think?

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java [hunk 3]
```diff
@@ -22,18 +22,49 @@
...
 
-    @Override
-    public void onConstruct(EnhancedInstance objInst, Object[] allArguments) {
-        ConsumerConfig config = (ConsumerConfig) allArguments[0];
-        // set the bootstrap server address
-        ConsumerEnhanceRequiredInfo requiredInfo = new ConsumerEnhanceRequiredInfo();
-        requiredInfo.setBrokerServers(config.getList("bootstrap.servers"));
-        requiredInfo.setGroupId(config.getString("group.id"));
+    @Override public void onConstruct(EnhancedInstance objInst, Object[] allArguments) {
+        ConsumerEnhanceRequiredInfo requiredInfo = resolveConsumerEnhanceRequiredInfo( allArguments[0] );
```
Comment (kezhenxu94) [inline apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:37]: Seems you're using a different code style, can you please import the [dedicated one](https://github.com/apache/skywalking/blob/master/codeStyle.xml) for SkyWalking to avoid unnecessary code changes?

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java (hunk 2 above)
Comment (kezhenxu94) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:50]: > This ConsumerConfig and Map logic should be separated into 2 interceptors, rather than using `instanceof` to check.
> Even here, we should not face performance impact as this is `KafkaConsumer` initialization, so wouldn't execute in high frequency, but still, better to avoid any tiny performance impact.
> @kezhenxu94 What do you think?

I'm +1

Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:50]: Will create new Interceptor.

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java (hunk 3 above)
Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:37]: Working on setting up checkstyle in my IDE.

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java (hunk 1 above)
Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java:32]: yep checkstyle maven plugin was failing. Will remove this in final pull request.

Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java]: Addressed in updated PR

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java (hunk 2 above)
Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java]: Updated the PR with two interceptors

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java (hunk 3 above)
Comment (divyakumarjain) [reply apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConsumerConstructorInterceptor.java]: checked all the modified with checkstyle rules

**Comment by divyakumarjain** [comment]
> `Supported-list.md` and `CHANGES.md` should be updated accordingly.

Updated in PR

**Comment by wu-sheng** [comment]
> 2021-04-26T14:57:50.5531515Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-kafka-plugin: You have 1 Checkstyle violation. -> [Help 1]

Still have a style issue.

**Comment by divyakumarjain** [comment]
Have updated the formatting to meet checkstyle rules.

File: apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConstructorWithConsumerConfigInterceptPoint.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+ *
+ */
+
+package org.apache.skywalking.apm.plugin.kafka;
+
+import org.apache.kafka.clients.consumer.ConsumerConfig;
+
+/**
+ *
+ **/
```
Comment (kezhenxu94) [inline apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/ConstructorWithConsumerConfigInterceptPoint.java:25]:
```suggestion
```

File: CHANGES.md [hunk 5]
```diff
@@ -16,6 +16,7 @@ Release Notes.
 * resolve agent has no retries if connect kafka cluster failed when bootstrap
 * Add Seata in the component definition. Seata plugin hosts on Seata project.
 * Extended Kafka plugin to properly trace consumers that have topic partitions directly assigned.
+* Support kafka consumer 2.8.0
```
Comment (kezhenxu94) [inline CHANGES.md:19]:
```suggestion
* Support Kafka consumer 2.8.0.
```

**Review by kezhenxu94 — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]
Once plugin test passed, I am good with this.
