### PR TITLE
Fix influxdb config resubmit

### LINKED ISSUE #5898: influxdb cluster as storage encounter many errors
###Requirement

we use influxdb srelay(https://github.com/toni-moreno/influxdb-srelay) for influxdb ha.but influxdb-sreay not support udp protocol.so a flag is required for skywalking influxdb plugin to turn off influxdb batch write.

### PR DESCRIPTION
**Pull request by zhangjianweibj**
Fix https://github.com/apache/skywalking/issues/5898

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #5898.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by dmsolr — APPROVED** [review]
LGTM
Thank you, @zhangjianweibj

File: oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/InfluxStorageConfig.java [hunk 1]
```diff
@@ -32,6 +32,7 @@
 
     private int actions;
     private int duration;
+    private boolean batchEnabled = true;
```
Comment (kezhenxu94) [inline oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/InfluxStorageConfig.java:35]: I believe you need to update the `application.yml` otherwise how could this take effect?

Comment (kezhenxu94) [reply oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/InfluxStorageConfig.java:35]: https://github.com/apache/skywalking/blob/127782f135223c2741c7c65a9d9386c49a8aa1be/oap-server/server-bootstrap/src/main/resources/application.yml#L187-L196

Comment (zhangjianweibj) [reply oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/InfluxStorageConfig.java:35]: ok,very thanks

File: oap-server/server-bootstrap/src/main/resources/application.yml [hunk 2]
```diff
@@ -192,6 +192,7 @@ storage:
     database: ${SW_STORAGE_INFLUXDB_DATABASE:skywalking}
     actions: ${SW_STORAGE_INFLUXDB_ACTIONS:1000} # the number of actions to collect
     duration: ${SW_STORAGE_INFLUXDB_DURATION:1000} # the time to wait at most (milliseconds)
+    batchEnabled: ${SW_STORAGE_INFLUXDB_BATCH_ENABLED:true}
```
Comment (wu-sheng) [inline oap-server/server-bootstrap/src/main/resources/application.yml:195]: Update `configuration-vocabulary.md` by following this change.

**Review by wu-sheng — APPROVED** [review]
