### PR TITLE
Set the length of event#parameters to 2000

### LINKED ISSUE #8608: [Bug] Length of column events.parameters is too small to hold "Start Java Application" event with long JAVA_OPTS
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When start a Java application with skywalking javaagent, events are failed to insert into table 'events' because the length of column 'parameters' is 1024 only.
e.g. My application has a very-long "JAVA_OPTS" generated by the IDE, see the attachment

screenshot

### What you expected to happen

1. extend the length of 'events.parameters' or
2. just truncate the input for walk-through

### How to reproduce

Start a Java app. with long JAVA_OPTS

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mustangxu**
### Fix <bug description or the bug issue number or bug issue link>
- [x] Add a unit test to verify that the fix works.
- [ ] Explain briefly why the bug exists and how to fix it.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #8608.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

File: oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    public void test() throws Exception {
+        new DefaultScopeDefine.Listener().notify(Event.class);
+        Model m = new StorageModels().add(Event.class, DefaultScopeDefine.EVENT,
+            new Storage(null, false, null), false);
+
+        m.getColumns().stream()
+            .filter(c -> Event.PARAMETERS.equals(c.getColumnName().getName()))
+            .findAny().ifPresent(c -> {
+                String sql = new TestTableInstaller().getColumn(c);
+//                System.out.println(sql);
```
Comment (wu-sheng) [inline oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java:25]: Please remove this.

File: oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+                Assert.assertTrue("Should contains 'TEXT'",
+                    sql.contains("TEXT"));
```
Comment (wu-sheng) [inline oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java:27]: I think we have a type mapping method, don't have to test in a separate UT.

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/model/ModelInstaller.java [hunk 3]
```diff
@@ -62,7 +62,7 @@ public void whenCreating(Model model) throws StorageException {
      * Installer implementation could use this API to request a column name replacement. This method delegates for
      * {@link ModelManipulator}.
      */
-    protected final void overrideColumnName(String columnName, String newName) {
+    protected void overrideColumnName(String columnName, String newName) {
```
Comment (wu-sheng) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/model/ModelInstaller.java:65]: Don't recommend this change as UT seems not necessary.

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/Event.java [hunk 4]
```diff
@@ -99,7 +99,7 @@ protected String id0() {
     @Column(columnName = MESSAGE)
     private String message;
 
-    @Column(columnName = PARAMETERS, storageOnly = true, length = 1024)
+    @Column(columnName = PARAMETERS, storageOnly = true, length = 20000)
```
Comment (wu-sheng) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/Event.java:102]: I think we need to control length in serialization process too? Otherwise still could have over length.

**Review by wu-sheng — COMMENTED** [review]
Comments added, and you should update change logs.

File: oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java (hunk 2 above)
Comment (wu-sheng) [reply oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/test/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/mysql/MySQLTableInstallerTest.java:27]: `MySQLTableInstaller#getColumn` is the source of column type. If you want to add a UT, add it for MySQLTableInstaller.

**Comment by wu-sheng** [comment]
@mustangxu Are you going to follow the comments?

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/model/ModelInstaller.java (hunk 3 above)
Comment (wu-sheng) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/model/ModelInstaller.java:65]:
```suggestion
    protected final void overrideColumnName(String columnName, String newName) {
```

**Review by wu-sheng — APPROVED** [review]
Merging for now as the author has no reponse. I will send a pull request to truncate the parameter.

**Review by wu-sheng — APPROVED** [review]
