### PR TITLE
Log harmless exception in DEBUG level

### LINKED ISSUE #4155: Decrease log level when byte buddy failed to match type
https://github.com/apache/skywalking/blob/8a97aad021b16eb72591323691e902b06bd54087/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java#L45-L51

I'd like to raise a discussion on the log level in the above code snippet.

For some reasons, in some of our applications, we have many classes that are failed to be resolved by byte buddy, and cases are that the applications all work well including the SkyWalking agent, but the logs are somewhat overwhelming, I've found an old issue https://github.com/raphw/byte-buddy/issues/373 , and seems this exception is mostly harmless, so I'm wondering whether we could just log this kind of logs in `DEBUG` level, what's your opinion, @wu-sheng @ascrutae @JaredTan95 @dmsolr @arugal etc.

### PR DESCRIPTION
**Pull request by kezhenxu94**
Yet users can still troubleshoot by looking into the log keywords `ProtectiveShieldMatcher : Byte-buddy occurs exception when match type: Cannot resolve type description for ...`

closes #4155

### CODE REVIEW

File: apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java [hunk 1]
```diff
@@ -46,7 +46,7 @@ public boolean matches(T target) {
         try {
             return this.matcher.matches(target);
         } catch (Throwable t) {
-            logger.warn(t, "Byte-buddy occurs exception when match type.");
+            logger.debug("Byte-buddy occurs exception when match type: {}", t.getMessage());
```
Comment (wu-sheng) [inline apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java]: Maybe it is better to use `if logger.debugenable` then `logger.warn`? The debug log like this will miss the error stack.

Comment (kezhenxu94) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java]: > Maybe it is better to use `if logger.debugenable` then `logger.warn`? The debug log like this will miss the error stack.

What I meant is to eliminate the stack traces, they look overwhelming and make users think that the agent is not working well

And the log level is `DEBUG` by default, `if (logger.isDebugEnable) then logger.warn` behaves the same as before

Comment (wu-sheng) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java]: I just have concerns about no stack when we really need this.

Comment (kezhenxu94) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java]: > I just have concerns about no stack when we really need this.

I had looked carefully into the stack traces when I wanted to find out why it really failed, and I'm sure the stack traces don't help at all.

So what about overloading a `debug` method with `Throwable`, and making the log level default to `INFO`?

Comment (kezhenxu94) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java]: I mean:

```java
if (logger.isDebugEnabled()) {
    logger.debug(throwable, "xxx")
}
```

File: apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/api/ILog.java [hunk 2]
```diff
@@ -51,5 +51,10 @@
 
     void debug(String format, Object... arguments);
 
+    default void debug(Throwable t, String format, Object... arguments) {
```
Comment (wu-sheng) [inline apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/api/ILog.java]: this `default` for?

Comment (kezhenxu94) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/api/ILog.java]: > this `default` for?

There’re many anonymous inner classes implementing this interface in unit test, I just don’t want to implement this method there over and over, it’s useless

Comment (wu-sheng) [reply apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/api/ILog.java]: This is not a good start for the codes. Others may refer to this in further PRs.
