### PR TITLE
Fix potential gRPC connection leak(not closed) for the channels among OAP instances. 

### LINKED ISSUE #5993: [Bug]Why does the k8s cluster deployment start an error
### Bug
-Use skywalking-kubernetes helm to deploy in k8s

The following error message appears every time you start

`2020-12-11 09:13:56,370 - org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager -20470 [pool-5-thread-1] ERROR [] - Self remote client invoked to close.
org.apache.skywalking.oap.server.core.UnexpectedException: Self remote client invoked to close.
	at org.apache.skywalking.oap.server.core.remote.client.SelfRemoteClient.close(SelfRemoteClient.java:60) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.lambda$reBuildRemoteClients$8(RemoteClientManager.java:234) ~[server-core-8.3.0.jar:8.3.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.reBuildRemoteClients(RemoteClientManager.java:234) ~[server-core-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:137) [server-core-8.3.0.jar:8.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

Is it related to the self.yaml configuration file? If it should be modified

I enabled Self Observability according to the document, this error still exists, but self.yaml is not modified

### PR DESCRIPTION
**Pull request by wu-sheng**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #5993.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

Fix potential gRPC connection leak(not closed) for the channels among OAP instances. The `self` client should not close due to this in SelfRemoteClient. I add a filter to avoid this call.
```java
    @Override
    public void close() {
        throw new UnexpectedException("Self remote client invoked to close.");
    }
```

### CODE REVIEW

**Review by kezhenxu94 — DISMISSED** [review]
LGTM

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java [hunk 1]
```diff
@@ -230,7 +246,10 @@ private void reBuildRemoteClients(List<RemoteInstance> remoteInstances) {
 
         remoteClientCollection.values()
                               .stream()
-                              .filter(remoteClientAction -> remoteClientAction.getAction().equals(Action.Close))
+                              .filter(remoteClientAction ->
+                                          remoteClientAction.getAction().equals(Action.Close)
+                                              && !remoteClientAction.getRemoteClient().getAddress().isSelf()
```
Comment (hanahmily) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java:251]:
```suggestion
                                              && 
remoteClientAction.getRemoteClient() != null
                                              &&                                           !remoteClientAction.getRemoteClient().getAddress().isSelf()
```

Comment (wu-sheng) [reply oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java:251]: This would not be null. I enhanced another by following `Filter OAP instances(unassigned in booting stage) of the empty IP in KubernetesCoordinator`.

**Review by hanahmily — APPROVED** [review]
LGTM
