### PR TITLE
BanyanDB: support using native term searching for `keyword` in query `findEndpoint` and `getAlarm`.

### LINKED ISSUE #12592: [Bug] BanyanDB Module in OAP Not Using Native Term Searching
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I've noticed that the BanyanDB module in OAP does not utilize the database's native term searching for certain scenarios, particularly endpoint name matching. It would be beneficial to incorporate native term searching and add annotation to mark the index rule for analyzing those tags. This enhancement would improve the module's functionality in handling endpoint name matching.

In the table creation procedure, to set the [analyzer](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/model/v1/query.proto#L65) to the indexRule. We should use the [simple](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L180) analyzer.

Query operation should use the [match](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/model/v1/query.proto#L65) binary operator to search the index.

### What you expected to happen

Nan

### How to reproduce

Nan

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wankai123**
- [X] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #12592.
- [X] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/annotation/BanyanDB.java [hunk 1]
```diff
@@ -177,4 +177,34 @@ enum IndexType {
...
+    /**
+     * Match query is designed for BanyanDB match query with specific analyzer. It is a fuzzy query implementation
+     * powered by analyzer.
+     *
+     * @since 10.1.0
+     */
+    @Target({ElementType.FIELD})
+    @Retention(RetentionPolicy.RUNTIME)
+    @interface MatchQuery {
+        AnalyzerType analyzer() default AnalyzerType.ANALYZER_SIMPLE;
```
Comment (wu-sheng) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/annotation/BanyanDB.java:190]: As @hanahmily is adding a more correct analyzer, I think we should consider no default for this annotation.

**Comment by wu-sheng** [comment]
Let's wait for another server patch and next client rc.

File: oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/alarm/AlarmRecord.java [hunk 2]
```diff
@@ -82,6 +82,7 @@ public StorageID id() {
     private long startTime;
     @Column(name = ALARM_MESSAGE, length = 512)
     @ElasticSearch.MatchQuery
+    @BanyanDB.MatchQuery(analyzer = BanyanDB.MatchQuery.AnalyzerType.ANALYZER_SIMPLE)
```
Comment (wu-sheng) [inline oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/alarm/AlarmRecord.java:85]:
```suggestion
    @BanyanDB.MatchQuery(analyzer = BanyanDB.MatchQuery.AnalyzerType.SIMPLE)
```

We could remove the prefix as the type indicated that.

**Review by wu-sheng — APPROVED** [review]
