### PR TITLE
Fix: MAL function would miss samples name after creating new samples.

### LINKED ISSUE #6857: how can i understand cpu useage? it looks like incorrect
Please answer these questions before submitting your issue.

___
### Question

in infrastructure monitoring 
how can i understand cpu useage?
it always 0.0 
___
image
here is the config:
image

otel-collector-config:
image

### PR DESCRIPTION
**Pull request by wankai123**
### Fix MAL function would miss samples name after creating new samples.
- [X] Add a unit test to verify that the fix works.
- [X] Explain briefly why the bug exists and how to fix it.
- [X] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6857
- [X] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

When MAL do `aggregate` like `sum/max/min` or do `avg`/`histogram`, there used `InternalOps.newSample`.
But this function missed the samples name:

image

That is impacted the `rate/irate/increase` functions because when we do increase count we use sample `name` and `labels` 
as the `id` to separate the samples.

image

So, in some scenario, for example:
```yaml
  - name: cpu_total_percentage
    exp: (node_cpu_seconds_total * 100).tagNotEqual('mode' , 'idle').sum(['node_identifier_host_name']).rate('PT1M')
  - name: disk_written
    exp: node_disk_written_bytes_total.sum(['node_identifier_host_name']).rate('PT1M')
```
These 2 expressions will make the samples have the same labels if the sample name missed, the `id` above would the same.
The cache and calculate of the value would incorrect, this caused issue #6857.

### CODE REVIEW

**Review by wu-sheng — DISMISSED** [review]
@hanahmily Please recheck.

File: oap-server/analyzer/meter-analyzer/src/test/java/org/apache/skywalking/oap/meter/analyzer/dsl/AggregationTest.java [hunk 1]
```diff
@@ -54,117 +54,117 @@
     @Parameterized.Parameters(name = "{index}: {0}")
     public static Collection<Object[]> data() {
         return Arrays.asList(new Object[][] {
-            {
+           /* {
```
Comment (kezhenxu94) [inline oap-server/analyzer/meter-analyzer/src/test/java/org/apache/skywalking/oap/meter/analyzer/dsl/AggregationTest.java:57]: Why comment out these cases?

Comment (wankai123) [reply oap-server/analyzer/meter-analyzer/src/test/java/org/apache/skywalking/oap/meter/analyzer/dsl/AggregationTest.java]: It's an omission，thanks @kezhenxu94 ，I have fixed it.

**Review by kezhenxu94 — APPROVED** [review]
