### PR TITLE
[ISSUE 5541] Fix H2 in-memory database table missing issues

### LINKED ISSUE #5541: Table "PROFILE_TASK" not found
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by coolbeevip**
### Fix H2 in-memory database table missing issues
- [x] Explain briefly about why the bug exists and how to fix it.

   Just add ;DB_CLOSE_DELAY=-1 to the database URL for H2StorageConfig
   
   See the [In-Memory Databases](http://h2database.com/html/features.html#in_memory_databases) section of the Features page. To quote:
   > By default, closing the last connection to a database closes the database. For an in-memory database, this means the content is lost. To keep the database open, add ;DB_CLOSE_DELAY=-1 to the database URL. To keep the content of an in-memory database as long as the virtual machine is alive, use jdbc:h2:mem:test;DB_CLOSE_DELAY=-1.
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #5541 
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

File: oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/H2StorageConfig.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
 @Getter
 public class H2StorageConfig extends ModuleConfig {
     private String driver = "org.h2.jdbcx.JdbcDataSource";
-    private String url = "jdbc:h2:mem:skywalking-oap-db";
+    private String url = "jdbc:h2:mem:skywalking-oap-db;DB_CLOSE_DELAY=-1";
```
Comment (wu-sheng) [inline oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/H2StorageConfig.java:29]: Take a look at application.yml, I am feeling this will be overrided, and make no effect.

Comment (coolbeevip) [reply oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/H2StorageConfig.java:29]: Done. thank you for reminding me

**Review by wu-sheng — APPROVED** [review]

**Review by kezhenxu94 — APPROVED** [review]
Thanks
